CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE
);

-- Nutrition values are per 100g.
CREATE TABLE products (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id  BIGINT        NOT NULL REFERENCES categories (id),
    name         VARCHAR(200)  NOT NULL,
    slug         VARCHAR(200)  NOT NULL UNIQUE,
    description  VARCHAR(2000) NOT NULL,
    origin       VARCHAR(100),
    price        BIGINT        NOT NULL,
    weight_grams INT           NOT NULL,
    stock        INT           NOT NULL DEFAULT 0,
    image_url    VARCHAR(500),
    calories     NUMERIC(6, 1) NOT NULL,
    protein      NUMERIC(5, 1) NOT NULL,
    fat          NUMERIC(5, 1) NOT NULL,
    carbs        NUMERIC(5, 1) NOT NULL,
    fiber        NUMERIC(5, 1) NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_products_category ON products (category_id);
