package com.nutshop.cart;

import jakarta.validation.Valid;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.util.List;

/**
 * Requests carry only product ids and quantities. Any price, name or stock a client sends is ignored (unknown JSON
 * fields are dropped); the server always reads them from the products table.
 */
public final class CartDtos {

	/** Hard ceiling for request validation; the configured cart.max-qty-per-item is applied on top. */
	static final int QTY_CEILING = 99;
	static final int MAX_LINES = 50;

	private CartDtos() {
	}

	public record AddItemRequest(
			@NotNull(message = "Thiếu mã sản phẩm") Long productId,
			@NotNull(message = "Vui lòng chọn số lượng")
			@Min(value = 1, message = "Số lượng phải lớn hơn 0")
			@Max(value = QTY_CEILING, message = "Số lượng quá lớn") Integer quantity) {
	}

	/** 0 removes the line. */
	public record SetQuantityRequest(
			@NotNull(message = "Vui lòng chọn số lượng")
			@Min(value = 0, message = "Số lượng không được âm")
			@Max(value = QTY_CEILING, message = "Số lượng quá lớn") Integer quantity) {
	}

	public record LineRequest(
			@NotNull(message = "Thiếu mã sản phẩm") Long productId,
			@NotNull(message = "Vui lòng chọn số lượng")
			@Min(value = 1, message = "Số lượng phải lớn hơn 0")
			@Max(value = QTY_CEILING, message = "Số lượng quá lớn") Integer quantity) {
	}

	/**
	 * @param mergeKey generated by the client for its guest cart; retrying with the same key never adds twice
	 */
	public record MergeRequest(
			@NotBlank(message = "Thiếu mã gộp giỏ hàng") @Size(max = 100, message = "Mã gộp giỏ hàng quá dài") String mergeKey,
			@NotNull(message = "Thiếu danh sách sản phẩm")
			@Size(max = MAX_LINES, message = "Giỏ hàng tối đa 50 sản phẩm") List<@Valid LineRequest> items) {
	}

	public record ValidateRequest(
			@NotNull(message = "Thiếu danh sách sản phẩm")
			@Size(max = MAX_LINES, message = "Giỏ hàng tối đa 50 sản phẩm") List<@Valid LineRequest> items) {
	}

	public enum LineStatus {
		/** Can be bought as is. */
		OK,
		/** Current price differs from the price when it was added (current price is used). */
		PRICE_CHANGED,
		/** Wanted more than can be bought now; quantity shown/charged is reduced to maxPurchasable. */
		QTY_REDUCED,
		OUT_OF_STOCK,
		/** Discontinued or no longer exists. */
		UNAVAILABLE
	}

	/**
	 * @param price current price (VND); priceAtAdd is null for guest carts
	 * @param quantity quantity counted in totals (requestedQuantity reduced to maxPurchasable if needed)
	 * @param requestedQuantity quantity stored in the cart
	 * @param lineTotal price x quantity, 0 for lines that cannot be bought
	 */
	public record CartLine(Long productId, String name, String slug, String imageUrl, String categorySlug,
			Integer weightGrams, long price, Long priceAtAdd, int quantity, int requestedQuantity, int maxPurchasable,
			long lineTotal, LineStatus status) {
	}

	/**
	 * @param amountToFreeShipping how much more to spend for free shipping (0 when already free or cart is empty)
	 * @param canCheckout false when empty or any line is OUT_OF_STOCK / UNAVAILABLE
	 */
	public record CartView(List<CartLine> items, int totalQuantity, long subtotal, long shippingFee,
			long amountToFreeShipping, long freeShippingThreshold, long total, boolean canCheckout) {
	}

	/** A non-blocking notice, e.g. the quantity was capped at what is available. */
	public record CartWarning(String code, String message, Long productId, Integer limitedTo) {
	}

	public record CartMutationResponse(CartView cart, CartWarning warning) {
	}

	public record SkippedLine(Long productId, String code, String message) {
	}

	/**
	 * @param alreadyMerged true when this mergeKey was applied before (nothing was added this time)
	 */
	public record MergeResponse(CartView cart, List<SkippedLine> skipped, boolean alreadyMerged) {
	}
}
